language: generic

sudo: required

services:
  - docker

before_install:
  - docker build -t jeckson/react-full-app -f ./frontend/Dockerfile.dev ./frontend

script:
  - docker run -e CI=true jeckson/react-full-app npm run test

after_success:
  - docker build -t jeckson/docker-frontend ./frontend
  - docker build -t jeckson/docker-backend ./backend
  - docker build -t jeckson/docker-mysql ./mysql
  - docker build -t jeckson/docker-nginx ./nginx

  - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_ID" --password-stdin

  - docker push jeckson/docker-frontend 
  - docker push jeckson/docker-backend 
  - docker push jeckson/docker-mysql 
  - docker push jeckson/docker-nginx